# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: ğŸ§  MIND Group
    url: /#top
    weight: 10
  - name: âœ… Solutions
    weight: 20
  - parent: Solutions
    name: ğŸ” Research
    url: research/
    weight: 30
  - parent: Solutions
    name: ğŸ“’ï¸ Educational
    url: educational/
    wight: 40
  - parent: Solutions
    name: ğŸ“ Clinical
    url: clinical/
    weight: 50
  - name: ğŸ‘¥ Meet us
    url: /#top
    weight: 60
  - name: ğŸ“¨ Contact
    weight: 70
    hasChildren: true
  - parent: Resources
    name: Blog
    url: blog/
